### ISSUE TITLE
Cloudinary

### ISSUE THREAD

**Issue by kschmitz123** [kschmitz123/diy-project-app#19]
# User-Story

As a developer

I want to connect to cloudinary

so that users can upload images

# Notes, Links, Material
https://www.youtube.com/watch?v=Rw_QeJLnCK4&t=9s
https://github.com/jamesqquick/cloudinary-react-and-node

# ToDos

- [x] Create cloudinary account
- [x] Click on Select Image should open folder to select image
- [x] Create display container for selected image
- [x] Click on Upload should upload image to cloudinary
- [x] Connect to cloudinary
- [x] Write post function
- [x] Error handling
- [x] Get back image url from cloudinary (for mongoDB)
