### ISSUE TITLE
Basic setup

### ISSUE THREAD

**Issue by kschmitz123** [kschmitz123/diy-project-app#22]
# User-Story

As a developer

I want to clean up my starter code

so that i can start building my app

# Notes, Links, Material

# ToDos

- [x] Remove unnecessary code
- [x] Rename project (index.html)
- [x] Add own folder structure
