### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by kschmitz123** [kschmitz123/diy-project-app#3]
# User-Story

As a user

I want to have a navbar

so that i can easily navigate from one page to another

# Notes, Links, Material

![image](https://user-images.githubusercontent.com/70961229/99961735-35bbb780-2d8f-11eb-84ed-554efd5145e8.png)

# ToDos

- [x] Add home symbol
- [x] Add favorite symbol
- [x] Add plus symbol
