### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by kschmitz123** [kschmitz123/diy-project-app#33]
# User-Story

As a user

I want to be able to  upload projects

# Notes, Links, Material

https://www.npmjs.com/package/json-server

# ToDos

- [x] Install json server
- [x] Add db.json
- [ ] Configure routes (upload, search/filter, delete?)
