### ISSUE TITLE
Favourites

### ISSUE THREAD

**Issue by kschmitz123** [kschmitz123/diy-project-app#38]
# User-Story

As a user

I want to mark project as favourite

so that i can have a look at them again

# Notes, Links, Material

# ToDos

- [ ] add favourites to localstorage
- [ ] get favourites from localstorage
- [ ] change color of heart when saved to favourites
