### ISSUE TITLE
User Login Authentification

### ISSUE THREAD

**Issue by kschmitz123** [kschmitz123/diy-project-app#50]
# User-Story

As a user

I want to be able to login

so that i can edit my projects and see my favourites

# Notes, Links, Material

https://soshace.com/react-user-login-authentication-using-usecontext-and-usereducer/
https://dev.to/curtiscodes/learn-to-usecontext-with-hooks-in-3-minutes-4c4g

# ToDos

- [x] add functionality to login
- [x] create user collection in mongoDB
- [ ] create and append json web token
- [x]  check if new user or existing user
- [x]  encrypt password
