### ISSUE TITLE
Style fixes

### ISSUE THREAD

**Issue by kschmitz123** [kschmitz123/diy-project-app#67]
# Notes, Links, Material

# ToDos

- [x] Fix buttons on "delete" popup
- [x] Disable background when popup is open
- [x] Style error messages on login screen
- [x] Remove link style from project title
- [x] add app icon
