### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by kschmitz123** [kschmitz123/diy-project-app#71]
# Notes, Links, Material

# ToDos

- [x] create read.me
- [x] add .env.example
- [x] add app preview
